### ISSUE TITLE
Update to NServiceBus v6

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#22]
Task force: @scooletz @dvdstelt @SeanFeldman @yvesgoeleven
Connects to: Particular/PlatformDevelopment#182

This is the AzureStorageQueues adapter epic which incorporates the work for making the ASQ transport work with core v6.

- [x] Upgrade to core v6 #28
- [x] Upgrade Azure Storage Dependency to latest major range https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/23
- [x] Async/await support https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/20
- [x] Code only configuration https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/24
- [x] Get rid of transaction scopes & IEnlistmentNotification https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/26
- [x] Replacing MD5 with SHA1 https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/25
- [x] Log properly failed send operations #19 
- [x] Mark develop as 7.0 https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/35
- [x] Remove ASQ native purge, use core one instead https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/3
- [x] Remove the dependency on the core serializer #29 
- [x] ~~Consider using `TestIndependenceBehavior` instead of long-lasting `ClearAsync` #36~~
- [x]  Map namespace name to connectionstring #27 
- [x] Handle TransportTransactionMode.None as at-most-once #53
- [ ] Review 'Public' https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/43
- [x] Bump up core #47
- [ ] Multi namespace support @melkio #21

**Comment by andreasohlund** [comment]
@Scooletz given that you are now working on the saga persisters would you say that this one is no longer in progress?

**Comment by Scooletz** [comment]
I wanted to finish the #27 but it looks that this PR will need more polishing. We can park this till Saga persisters are done.

**Comment by andreasohlund** [comment]
So remove the `In progress` label?

**Comment by Scooletz** [comment]
Done.

**Comment by dvdstelt** [comment]
Why was this opened again? I'd say we close this and keep #21 and #43 open.

**Comment by andreasohlund** [comment]
Closing this one, #21 and #43 tracks outstanding work
