### ISSUE TITLE
Disabling delayed delivery polling to save Storage costs

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#250]
Endpoints that do not utilize delayed delivery (example [here](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/248)) would not poll delayed delivery infrastructure to save Storage costs. 

Should an endpoint start leveraging delayed delivery, the transport should throw an exception to let know that disabling delayed delivery should not take place.

Configuration could look like the following:

```c#
var transport = endpointConfiguration.UseTransport<AzureStorageQueueTransport>();
var delayedDelivery = transport.DelayedDelivery();
delayedDelivery.DisableDelayedDelivery()
```

### PoA

- [x] Make the setting mandatory - **PR** #264
- [x] Add to the upgrade guide **PR** [#3233](https://github.com/Particular/docs.particular.net/pull/3233)
- [x] Update doco/samples **PR** [#3233](https://github.com/Particular/docs.particular.net/pull/3233)

**Comment by SeanFeldman** [comment]
There are 3 scenarios when a delayed message can appear:
1. Sending message with `SendOptions` in the future.
1. Requesting a saga timeout
1. Recoverability - delayed retries

Assuming we'll provide an option to disabled delayed delivery, we'd need to take into consideration the hybrid mode. In hybrid mode `TimeoutManager` is enabled along with native delayed delivery.

An approach to take, is to indicate to Core that delayed delivery is not supported. That way, Core will never give the transport any messages that need to be delayed. In addition to that, TM will need to be disabled, so that Core will not attempt to provide messages to the transport that are intended to be dispatched via TM. Core will throw an exception when either one of the 2 first above operations would be attended. For delayed retries, those would be disabled an messages would go to the error queue right after immediate retries are exhausted. The transport would **not** need to throw any exceptions.

**Comment by danielmarbach** [comment]
In essence you are saying when the `DisableDelayedDeliveryAndThrowExceptionIfUsed` is present we return on the transport infrastructure that we don't support delayed delivery and disable the timeout manager feature as well as the internal polling? If I understood you correctly that sounds like a very reasonable approach and leverages the core in a way it was built for.

**Comment by SeanFeldman** [comment]
That's exactly what I meant.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/e3db55ba50be963ea13c6545d10884388e52712e

**Comment by SeanFeldman** [comment]
doco not finished

**Comment by SeanFeldman** [comment]
Pending [doco PR](https://github.com/Particular/docs.particular.net/pull/3233) merge and then will close this.

**Comment by boblangley** [comment]
Doco PR was merged. Closing.
